#!/usr/bin/env bash

set -e

DIR=$(dirname "$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )")
CURR=$(pwd)
TARGETDIR=".${CURR#"$DIR"}"
cd "$DIR"

# TODO(vipa, 2023-05-15): We later want to transform arguments given
# after "--" to be resolved relative to $TARGETDIR but given to
# test-spec as relative to $DIR, but I don't know how to do that
# conveniently in bash atm, so I'm leaving it for now.
if [ ! "$DIR" -ef "$TARGETDIR" ]; then
  echo "ERROR: this test script only knows how to run tests while the working directory is the root of the repository."
  exit 1
fi

# NOTE(vipa, 2024-11-22): Unconditionally overwrite MCORE_LIBS, since
# tests should run with this value.
export MCORE_LIBS=stdlib=$DIR/src/stdlib

# NOTE(wmuth, 2025-03-27): Import utils, create cleaned args array (remove
# script flags), set vars
source "$DIR/misc/scripts/test-utils"
declare -a TEST_SPEC_ARGS
util_set_vars "$@"

if util_use_tup; then
  echo "Using 'tup' as a test runner"

  util_compile_test_spec

  if TUPTARGETS=`"$DIR/misc/test-spec" --tup-filter "${TEST_SPEC_ARGS}"`; then
      IFS=$'\n'
      exec tup $TUPTARGETS
  fi
else
  echo "Using 'make' as a test runner"
  if ! util_mi_exists; then
    message="The 'mi' you wanted does not exist. Would you like to compile/install it?"
    if util_user_consent "$message"; then
      util_install_desired_mi
    else
      echo "Please bootstrap or install the desired 'mi'."
      exit 1
    fi
  fi

  util_compile_test_spec

  if [[ ! (":$OCAMLPATH:" == *":$DIR/build/lib:"*) ]]; then
      export OCAMLPATH=$DIR/build/lib:$OCAMLPATH
  fi
  exec make -f <("$DIR/misc/test-spec" --make "${TEST_SPEC_ARGS[@]}")
fi
