#!/usr/bin/env bash

SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")

if [ $# -eq 0 ]; then
    dir=./*
else
    dir=$1
fi

comm -1 -3 <("$SCRIPT_DIR/repo-files" | sort) <(find $dir -type f | sed 's#^./##' | sort)
