-- Entry point for the `ecmascript` backend: compiles an MExpr AST to an
-- ECMAScript module and writes it to disk.
--
-- The generated module exports a single function taking the runtime
-- environment, so that a caller supplies the effectful operations -- how to
-- print, how to read a file, how to exit -- afresh on every execution.

include "common.mc"
include "ecmascript/compile.mc"
include "ecmascript/ident.mc"
include "ecmascript/pprint.mc"
include "ecmascript/runtime.mc"
include "option.mc"
include "string.mc"

lang MCoreCompileES = MExprESCompile + ESPrettyPrint
end

type CompileESOptions = {
  -- Where to write the module; defaults to the source path with a `.mjs`
  -- extension.
  output : Option String
}

let compileESOptionsEmpty : CompileESOptions = { output = None () }

-- Drops a trailing extension, if any.
let esStripExtension : String -> String = lam filename.
  match strLastIndex '.' filename with Some idx
  then subsequence filename 0 idx
  else filename

-- Compiles an MExpr AST to ECMAScript source text.
--
-- The pure runtime intrinsics the program used are appended *after* `main`.
-- That is safe because everything the compiler emits into the program body
-- lives inside `main`, and a host does not call `main` until the whole module
-- has evaluated -- by which point every definition below it is initialised.
let esCompileToString : use Ast in Expr -> String =
  lam ast.
  use MCoreCompileES in
  match compileESProg ast with (prog, usedRuntime) in
  match printESProg esNameEnvEmpty prog with (_, source) in
  concat source (esRuntimeEmit usedRuntime)

-- Compiles an MExpr AST and writes the module, returning the path written.
let compileMCoreToES : use Ast in CompileESOptions -> Expr -> String -> String =
  lam opts. lam ast. lam sourcePath.
  let targetPath =
    optionGetOr (concat (esStripExtension sourcePath) ".mjs") opts.output in
  let header = join
    ["// Generated by the Miking ecmascript backend from ", sourcePath, ".\n\n"] in
  writeFile targetPath (concat header (esCompileToString ast));
  printLn (concat "Successfully compiled file to: " targetPath);
  targetPath

mexpr

utest esStripExtension "foo/bar.mc" with "foo/bar" in
utest esStripExtension "foo/bar" with "foo/bar" in

--   let a = 1 in let b = 2 in let c = addi a b in dprint c
let a = nameSym "a" in
let b = nameSym "b" in
let c = nameSym "c" in
let ast = bindall_
  [ nulet_ a (int_ 1)
  , nulet_ b (int_ 2)
  , nulet_ c (addi_ (nvar_ a) (nvar_ b))
  ] (dprint_ (nvar_ c)) in

utest esCompileToString ast with join
  [ "export default function main(env) {\n"
  , "  const a = 1;\n"
  , "  const b = 2;\n"
  , "  const c = a + b;\n"
  , "  env.dprint(c);\n"
  , "}\n" ] in

-- Nested arithmetic keeps its precedence and needs no temporaries.
let d = nameSym "d" in
let ast2 = bind_ (nulet_ d (muli_ (addi_ (int_ 1) (int_ 2)) (int_ 3)))
                 (dprint_ (nvar_ d)) in
utest esCompileToString ast2 with join
  [ "export default function main(env) {\n"
  , "  const d = (1 + 2) * 3;\n"
  , "  env.dprint(d);\n"
  , "}\n" ] in

-- A binding in expression position is hoisted, not wrapped in an IIFE.
let e = nameSym "e" in
let ast3 = dprint_ (bind_ (nulet_ e (int_ 7)) (addi_ (nvar_ e) (int_ 1))) in
utest esCompileToString ast3 with join
  [ "export default function main(env) {\n"
  , "  const e = 7;\n"
  , "  env.dprint(e + 1);\n"
  , "}\n" ] in

-- Distinct names sharing a string are disambiguated rather than merged.
let x1 = nameSym "x" in
let x2 = nameSym "x" in
let ast4 = bindall_
  [ nulet_ x1 (int_ 1), nulet_ x2 (int_ 2) ]
  (dprint_ (addi_ (nvar_ x1) (nvar_ x2))) in
utest esCompileToString ast4 with join
  [ "export default function main(env) {\n"
  , "  const x = 1;\n"
  , "  const x_1 = 2;\n"
  , "  env.dprint(x + x_1);\n"
  , "}\n" ] in

-- A named function becomes an n-ary declaration, and a saturated call a plain
-- n-ary call rather than `f(1)(2)`.
let f = nameSym "f" in
let x = nameSym "x" in
let y = nameSym "y" in
let astFn = bind_ (nulet_ f (nulam_ x (nulam_ y (addi_ (nvar_ x) (nvar_ y)))))
                  (dprint_ (appf2_ (nvar_ f) (int_ 1) (int_ 2))) in
utest esCompileToString astFn with join
  [ "export default function main(env) {\n"
  , "  function f(x, y) {\n"
  , "    return x + y;\n"
  , "  }\n"
  , "  env.dprint(f(1, 2));\n"
  , "}\n" ] in

-- Applying it to too few arguments eta-expands, so the emitted n-ary function
-- is never called with a missing parameter.
let astPartial = bind_ (nulet_ f (nulam_ x (nulam_ y (addi_ (nvar_ x) (nvar_ y)))))
                       (dprint_ (app_ (nvar_ f) (int_ 1))) in
utest esCompileToString astPartial with join
  [ "export default function main(env) {\n"
  , "  function f(x, y) {\n"
  , "    return x + y;\n"
  , "  }\n"
  , "  env.dprint(a => f(1, a));\n"
  , "}\n" ] in

-- An alias inherits the arity it points at, so calls through it stay n-ary.
let g = nameSym "g" in
let astRef = bindall_
  [ nulet_ f (nulam_ x (nulam_ y (addi_ (nvar_ x) (nvar_ y))))
  , nulet_ g (nvar_ f) ]
  (dprint_ (appf2_ (nvar_ g) (int_ 1) (int_ 2))) in
utest esCompileToString astRef with join
  [ "export default function main(env) {\n"
  , "  function f(x, y) {\n"
  , "    return x + y;\n"
  , "  }\n"
  , "  const g = f;\n"
  , "  env.dprint(g(1, 2));\n"
  , "}\n" ] in

-- An anonymous lambda stays curried, since nothing tracks its arity.
let astAnon = dprint_ (app_ (nulam_ x (addi_ (nvar_ x) (int_ 1))) (int_ 2)) in
utest esCompileToString astAnon with join
  [ "export default function main(env) {\n"
  , "  env.dprint((x => x + 1)(2));\n"
  , "}\n" ] in

-- A constant condition folds away entirely.
let astIf = bind_ (nulet_ x (if_ true_ (int_ 1) (int_ 2))) (dprint_ (nvar_ x)) in
utest esCompileToString astIf with join
  [ "export default function main(env) {\n"
  , "  const x = 1;\n"
  , "  env.dprint(x);\n"
  , "}\n" ] in

-- When both arms only produce a value, statement position folds to a ternary
-- rather than a four-line `if`.
let a = nameSym "a" in
let astTernary = bindall_
  [ nulet_ a (int_ 5)
  , nulet_ x (if_ (lti_ (nvar_ a) (int_ 10)) (int_ 1) (int_ 2)) ]
  (dprint_ (nvar_ x)) in
utest esCompileToString astTernary with join
  [ "export default function main(env) {\n"
  , "  const a = 5;\n"
  , "  const x = a < 10 ? 1 : 2;\n"
  , "  env.dprint(x);\n"
  , "}\n" ] in

-- When an arm needs statements of its own it stays an `if`, with the binding
-- declared outside so it is still readable after the branch.
let z = nameSym "z" in
let astIfStmts = bindall_
  [ nulet_ a (int_ 5)
  , nulet_ x (if_ (lti_ (nvar_ a) (int_ 10))
                  (bind_ (nulet_ z (int_ 1)) (addi_ (nvar_ z) (nvar_ z)))
                  (int_ 2)) ]
  (dprint_ (nvar_ x)) in
utest esCompileToString astIfStmts with join
  [ "export default function main(env) {\n"
  , "  const a = 5;\n"
  , "  let x;\n"
  , "  if (a < 10) {\n"
  , "    const z = 1;\n"
  , "    x = z + z;\n"
  , "  } else {\n"
  , "    x = 2;\n"
  , "  }\n"
  , "  env.dprint(x);\n"
  , "}\n" ] in

-- In expression position with simple branches it is a ternary.
let astCond = dprint_ (if_ (lti_ (int_ 1) (int_ 2)) (int_ 1) (int_ 2)) in
utest esCompileToString astCond with join
  [ "export default function main(env) {\n"
  , "  env.dprint(1 < 2 ? 1 : 2);\n"
  , "}\n" ] in

-- An irrefutable pattern emits no branch at all, just the binding.
let astBind = dprint_ (match_ (int_ 3) (npvar_ x) (nvar_ x) never_) in
utest esCompileToString astBind with join
  [ "export default function main(env) {\n"
  , "  const x = 3;\n"
  , "  env.dprint(x);\n"
  , "}\n" ] in

-- Integer division truncates towards zero, as OCaml does; `Math.floor` would
-- disagree on every negative quotient.
let astDiv = dprint_ (divi_ (negi_ (int_ 7)) (int_ 2)) in
utest esCompileToString astDiv with join
  [ "export default function main(env) {\n"
  , "  env.dprint(Math.trunc(-7 / 2));\n"
  , "}\n" ] in

-- Floats share the `number` representation, so `int2float` is a no-op.
let astFloat = dprint_ (addf_ (int2float_ (int_ 1)) (float_ 0.5)) in
utest esCompileToString astFloat with join
  [ "export default function main(env) {\n"
  , "  env.dprint(1 + 0.5);\n"
  , "}\n" ] in

-- A Char is a one-character string.
let astChar = dprint_ (eqc_ (char_ 'a') (int2char_ (int_ 98))) in
utest esCompileToString astChar with join
  [ "export default function main(env) {\n"
  , "  env.dprint(\"a\" === String.fromCodePoint(98));\n"
  , "}\n" ] in

-- `floorfi` and `ceilfi` map straight onto the host, with no runtime helper.
let astFloor = dprint_ (floorfi_ (float_ 1.5)) in
let floored = esCompileToString astFloor in
let contains = lam needle. lam s. gti (length (strSplit needle s)) 1 in
utest contains "env.dprint(Math.floor(1.5));" floored with true in
utest contains "MExpr runtime intrinsics" floored with false in

-- A shift pulls its runtime definition in behind the program, along with the
-- helper it depends on.
let astShift = dprint_ (slli_ (int_ 2) (int_ 5)) in
let shifted = esCompileToString astShift in
utest contains "env.dprint($slli(2, 5));" shifted with true in
utest contains "function $slli(a, b) {" shifted with true in
utest contains "function $fromBig(x) {" shifted with true in
-- ... and nothing else from the runtime.
utest contains "function $roundfi" shifted with false in

-- A program using no runtime intrinsic gets no runtime section.
utest contains "MExpr runtime intrinsics" (esCompileToString astFn) with false in

-- A user binding named `env` does not capture the runtime environment.
let userEnv = nameSym "env" in
let ast5 = bind_ (nulet_ userEnv (int_ 1)) (dprint_ (nvar_ userEnv)) in
utest esCompileToString ast5 with join
  [ "export default function main(env) {\n"
  , "  const env_1 = 1;\n"
  , "  env.dprint(env_1);\n"
  , "}\n" ] in

()
