-- Entry point for the `ecmascript` backend: compiles an MExpr AST to an
-- ECMAScript module and writes it to disk.
--
-- The generated module exports a single function taking the runtime
-- environment, so that a caller supplies the effectful operations -- how to
-- print, how to read a file, how to exit -- afresh on every execution.

include "common.mc"
include "ecmascript/compile.mc"
include "ecmascript/ident.mc"
include "ecmascript/pprint.mc"
include "option.mc"
include "string.mc"

lang MCoreCompileES = MExprESCompile + ESPrettyPrint
end

type CompileESOptions = {
  -- Where to write the module; defaults to the source path with a `.mjs`
  -- extension.
  output : Option String
}

let compileESOptionsEmpty : CompileESOptions = { output = None () }

-- Drops a trailing extension, if any.
let esStripExtension : String -> String = lam filename.
  match strLastIndex '.' filename with Some idx
  then subsequence filename 0 idx
  else filename

-- Compiles an MExpr AST to ECMAScript source text.
let esCompileToString : use Ast in Expr -> String =
  lam ast.
  use MCoreCompileES in
  match printESProg esNameEnvEmpty (compileESProg ast) with (_, source) in
  source

-- Compiles an MExpr AST and writes the module, returning the path written.
let compileMCoreToES : use Ast in CompileESOptions -> Expr -> String -> String =
  lam opts. lam ast. lam sourcePath.
  let targetPath =
    optionGetOr (concat (esStripExtension sourcePath) ".mjs") opts.output in
  let header = join
    ["// Generated by the Miking ecmascript backend from ", sourcePath, ".\n\n"] in
  writeFile targetPath (concat header (esCompileToString ast));
  printLn (concat "Successfully compiled file to: " targetPath);
  targetPath

mexpr

utest esStripExtension "foo/bar.mc" with "foo/bar" in
utest esStripExtension "foo/bar" with "foo/bar" in

-- The step 1 acceptance program:
--   let a = 1 in let b = 2 in let c = addi a b in dprint c
let a = nameSym "a" in
let b = nameSym "b" in
let c = nameSym "c" in
let ast = bindall_
  [ nulet_ a (int_ 1)
  , nulet_ b (int_ 2)
  , nulet_ c (addi_ (nvar_ a) (nvar_ b))
  ] (dprint_ (nvar_ c)) in

utest esCompileToString ast with join
  [ "export default function main(env) {\n"
  , "  const a = 1;\n"
  , "  const b = 2;\n"
  , "  const c = a + b;\n"
  , "  env.dprint(c);\n"
  , "}\n" ] in

-- Nested arithmetic keeps its precedence and needs no temporaries.
let d = nameSym "d" in
let ast2 = bind_ (nulet_ d (muli_ (addi_ (int_ 1) (int_ 2)) (int_ 3)))
                 (dprint_ (nvar_ d)) in
utest esCompileToString ast2 with join
  [ "export default function main(env) {\n"
  , "  const d = (1 + 2) * 3;\n"
  , "  env.dprint(d);\n"
  , "}\n" ] in

-- A binding in expression position is hoisted, not wrapped in an IIFE.
let e = nameSym "e" in
let ast3 = dprint_ (bind_ (nulet_ e (int_ 7)) (addi_ (nvar_ e) (int_ 1))) in
utest esCompileToString ast3 with join
  [ "export default function main(env) {\n"
  , "  const e = 7;\n"
  , "  env.dprint(e + 1);\n"
  , "}\n" ] in

-- Distinct names sharing a string are disambiguated rather than merged.
let x1 = nameSym "x" in
let x2 = nameSym "x" in
let ast4 = bindall_
  [ nulet_ x1 (int_ 1), nulet_ x2 (int_ 2) ]
  (dprint_ (addi_ (nvar_ x1) (nvar_ x2))) in
utest esCompileToString ast4 with join
  [ "export default function main(env) {\n"
  , "  const x = 1;\n"
  , "  const x_1 = 2;\n"
  , "  env.dprint(x + x_1);\n"
  , "}\n" ] in

-- A user binding named `env` does not capture the runtime environment.
let userEnv = nameSym "env" in
let ast5 = bind_ (nulet_ userEnv (int_ 1)) (dprint_ (nvar_ userEnv)) in
utest esCompileToString ast5 with join
  [ "export default function main(env) {\n"
  , "  const env_1 = 1;\n"
  , "  env.dprint(env_1);\n"
  , "}\n" ] in

()
