-- Entry point for the `ecmascript` backend: compiles an MExpr AST to an
-- ECMAScript module and writes it to disk.
--
-- The generated module exports a single function taking the runtime
-- environment, so that a caller supplies the effectful operations -- how to
-- print, how to read a file, how to exit -- afresh on every execution.

include "common.mc"
include "ecmascript/cleanup.mc"
include "ecmascript/compile.mc"
include "ecmascript/ident.mc"
include "ecmascript/pprint.mc"
include "ecmascript/runtime.mc"
include "option.mc"
include "string.mc"

lang MCoreCompileES = MExprESCompile + ESPrettyPrint + ESCleanup
end

type CompileESOptions = {
  -- Where to write the module; defaults to the source path with a `.mjs`
  -- extension.
  output : Option String
}

let compileESOptionsEmpty : CompileESOptions = { output = None () }

-- Drops a trailing extension, if any.
let esStripExtension : String -> String = lam filename.
  match strLastIndex '.' filename with Some idx
  then subsequence filename 0 idx
  else filename

-- Compiles an MExpr AST to ECMAScript source text.
--
-- The pure runtime intrinsics the program used are appended *after* `main`.
-- That is safe because everything the compiler emits into the program body
-- lives inside `main`, and a host does not call `main` until the whole module
-- has evaluated -- by which point every definition below it is initialised.
let esCompileToString : use Ast in Expr -> String =
  lam ast.
  use MCoreCompileES in
  match compileESProg ast with (prog, usedRuntime) in
  -- Remove the scrutinee temporaries the pattern lowerer leaves behind, and
  -- the bindings record projection produces. See cleanup.mc.
  match printESProg esNameEnvEmpty (esCleanupProg prog) with (_, source) in
  concat source (esRuntimeEmit usedRuntime)

-- Compiles an MExpr AST and writes the module, returning the path written.
let compileMCoreToES : use Ast in CompileESOptions -> Expr -> String -> String =
  lam opts. lam ast. lam sourcePath.
  let targetPath =
    optionGetOr (concat (esStripExtension sourcePath) ".mjs") opts.output in
  let header = join
    ["// Generated by the Miking ecmascript backend from ", sourcePath, ".\n\n"] in
  writeFile targetPath (concat header (esCompileToString ast));
  printLn (concat "Successfully compiled file to: " targetPath);
  targetPath

mexpr

utest esStripExtension "foo/bar.mc" with "foo/bar" in
utest esStripExtension "foo/bar" with "foo/bar" in

--   let a = 1 in let b = 2 in let c = addi a b in dprint c
let a = nameSym "a" in
let b = nameSym "b" in
let c = nameSym "c" in
let ast = bindall_
  [ nulet_ a (int_ 1)
  , nulet_ b (int_ 2)
  , nulet_ c (addi_ (nvar_ a) (nvar_ b))
  ] (dprint_ (nvar_ c)) in

utest esCompileToString ast with join
  [ "export default function main(env) {\n"
  , "  const a = 1;\n"
  , "  const b = 2;\n"
  , "  const c = a + b;\n"
  , "  env.dprint(c);\n"
  , "}\n" ] in

-- Nested arithmetic keeps its precedence and needs no temporaries.
let d = nameSym "d" in
let ast2 = bind_ (nulet_ d (muli_ (addi_ (int_ 1) (int_ 2)) (int_ 3)))
                 (dprint_ (nvar_ d)) in
utest esCompileToString ast2 with join
  [ "export default function main(env) {\n"
  , "  const d = (1 + 2) * 3;\n"
  , "  env.dprint(d);\n"
  , "}\n" ] in

-- A binding in expression position is hoisted, not wrapped in an IIFE.
let e = nameSym "e" in
let ast3 = dprint_ (bind_ (nulet_ e (int_ 7)) (addi_ (nvar_ e) (int_ 1))) in
utest esCompileToString ast3 with join
  [ "export default function main(env) {\n"
  , "  const e = 7;\n"
  , "  env.dprint(e + 1);\n"
  , "}\n" ] in

-- Distinct names sharing a string are disambiguated rather than merged.
let x1 = nameSym "x" in
let x2 = nameSym "x" in
let ast4 = bindall_
  [ nulet_ x1 (int_ 1), nulet_ x2 (int_ 2) ]
  (dprint_ (addi_ (nvar_ x1) (nvar_ x2))) in
utest esCompileToString ast4 with join
  [ "export default function main(env) {\n"
  , "  const x = 1;\n"
  , "  const x_1 = 2;\n"
  , "  env.dprint(x + x_1);\n"
  , "}\n" ] in

-- A named function becomes an n-ary declaration, and a saturated call a plain
-- n-ary call rather than `f(1)(2)`.
let f = nameSym "f" in
let x = nameSym "x" in
let y = nameSym "y" in
let astFn = bind_ (nulet_ f (nulam_ x (nulam_ y (addi_ (nvar_ x) (nvar_ y)))))
                  (dprint_ (appf2_ (nvar_ f) (int_ 1) (int_ 2))) in
utest esCompileToString astFn with join
  [ "export default function main(env) {\n"
  , "  function f(x, y) {\n"
  , "    return x + y;\n"
  , "  }\n"
  , "  env.dprint(f(1, 2));\n"
  , "}\n" ] in

-- Applying it to too few arguments eta-expands, so the emitted n-ary function
-- is never called with a missing parameter.
let astPartial = bind_ (nulet_ f (nulam_ x (nulam_ y (addi_ (nvar_ x) (nvar_ y)))))
                       (dprint_ (app_ (nvar_ f) (int_ 1))) in
utest esCompileToString astPartial with join
  [ "export default function main(env) {\n"
  , "  function f(x, y) {\n"
  , "    return x + y;\n"
  , "  }\n"
  , "  env.dprint(a => f(1, a));\n"
  , "}\n" ] in

-- An alias inherits the arity it points at, so the call through it is n-ary
-- rather than curried. The alias binding itself is then removed, since a
-- second name for `f` says nothing `f` does not.
let g = nameSym "g" in
let astRef = bindall_
  [ nulet_ f (nulam_ x (nulam_ y (addi_ (nvar_ x) (nvar_ y))))
  , nulet_ g (nvar_ f) ]
  (dprint_ (appf2_ (nvar_ g) (int_ 1) (int_ 2))) in
utest esCompileToString astRef with join
  [ "export default function main(env) {\n"
  , "  function f(x, y) {\n"
  , "    return x + y;\n"
  , "  }\n"
  , "  env.dprint(f(1, 2));\n"
  , "}\n" ] in

-- An anonymous lambda stays curried, since nothing tracks its arity.
let astAnon = dprint_ (app_ (nulam_ x (addi_ (nvar_ x) (int_ 1))) (int_ 2)) in
utest esCompileToString astAnon with join
  [ "export default function main(env) {\n"
  , "  env.dprint((x => x + 1)(2));\n"
  , "}\n" ] in

-- A constant condition folds away entirely.
let astIf = bind_ (nulet_ x (if_ true_ (int_ 1) (int_ 2))) (dprint_ (nvar_ x)) in
utest esCompileToString astIf with join
  [ "export default function main(env) {\n"
  , "  const x = 1;\n"
  , "  env.dprint(x);\n"
  , "}\n" ] in

-- When both arms only produce a value, statement position folds to a ternary
-- rather than a four-line `if`.
let a = nameSym "a" in
let astTernary = bindall_
  [ nulet_ a (int_ 5)
  , nulet_ x (if_ (lti_ (nvar_ a) (int_ 10)) (int_ 1) (int_ 2)) ]
  (dprint_ (nvar_ x)) in
utest esCompileToString astTernary with join
  [ "export default function main(env) {\n"
  , "  const a = 5;\n"
  , "  const x = a < 10 ? 1 : 2;\n"
  , "  env.dprint(x);\n"
  , "}\n" ] in

-- When an arm needs statements of its own it stays an `if`, with the binding
-- declared outside so it is still readable after the branch.
let z = nameSym "z" in
let astIfStmts = bindall_
  [ nulet_ a (int_ 5)
  , nulet_ x (if_ (lti_ (nvar_ a) (int_ 10))
                  (bind_ (nulet_ z (int_ 1)) (addi_ (nvar_ z) (nvar_ z)))
                  (int_ 2)) ]
  (dprint_ (nvar_ x)) in
utest esCompileToString astIfStmts with join
  [ "export default function main(env) {\n"
  , "  const a = 5;\n"
  , "  let x;\n"
  , "  if (a < 10) {\n"
  , "    const z = 1;\n"
  , "    x = z + z;\n"
  , "  } else {\n"
  , "    x = 2;\n"
  , "  }\n"
  , "  env.dprint(x);\n"
  , "}\n" ] in

-- In expression position with simple branches it is a ternary.
let astCond = dprint_ (if_ (lti_ (int_ 1) (int_ 2)) (int_ 1) (int_ 2)) in
utest esCompileToString astCond with join
  [ "export default function main(env) {\n"
  , "  env.dprint(1 < 2 ? 1 : 2);\n"
  , "}\n" ] in

-- An irrefutable pattern emits no branch at all, just the binding.
let astBind = dprint_ (match_ (int_ 3) (npvar_ x) (nvar_ x) never_) in
utest esCompileToString astBind with join
  [ "export default function main(env) {\n"
  , "  const x = 3;\n"
  , "  env.dprint(x);\n"
  , "}\n" ] in

-- Integer division truncates towards zero, as OCaml does; `Math.floor` would
-- disagree on every negative quotient.
let astDiv = dprint_ (divi_ (negi_ (int_ 7)) (int_ 2)) in
utest esCompileToString astDiv with join
  [ "export default function main(env) {\n"
  , "  env.dprint(Math.trunc(-7 / 2));\n"
  , "}\n" ] in

-- Floats share the `number` representation, so `int2float` is a no-op.
let astFloat = dprint_ (addf_ (int2float_ (int_ 1)) (float_ 0.5)) in
utest esCompileToString astFloat with join
  [ "export default function main(env) {\n"
  , "  env.dprint(1 + 0.5);\n"
  , "}\n" ] in

-- A Char is a one-character string.
let astChar = dprint_ (eqc_ (char_ 'a') (int2char_ (int_ 98))) in
utest esCompileToString astChar with join
  [ "export default function main(env) {\n"
  , "  env.dprint(\"a\" === String.fromCodePoint(98));\n"
  , "}\n" ] in

-- `floorfi` and `ceilfi` map straight onto the host, with no runtime helper.
let astFloor = dprint_ (floorfi_ (float_ 1.5)) in
let floored = esCompileToString astFloor in
let contains = lam needle. lam s. gti (length (strSplit needle s)) 1 in
utest contains "env.dprint(Math.floor(1.5));" floored with true in
utest contains "MExpr runtime intrinsics" floored with false in

-- A shift pulls its runtime definition in behind the program, along with the
-- helper it depends on.
let astShift = dprint_ (slli_ (int_ 2) (int_ 5)) in
let shifted = esCompileToString astShift in
utest contains "env.dprint($slli(2, 5));" shifted with true in
utest contains "function $slli(a, b) {" shifted with true in
utest contains "function $fromBig(x) {" shifted with true in
-- ... and nothing else from the runtime.
utest contains "function $roundfi" shifted with false in

-- A program using no runtime intrinsic gets no runtime section.
utest contains "MExpr runtime intrinsics" (esCompileToString astFn) with false in

-- ---------------------------------------------------------------------
-- Records and tuples
-- ---------------------------------------------------------------------

-- A record is an object literal. Fields are sorted so output is stable, since
-- `mapBindings` order follows interned SIDs and is otherwise arbitrary.
let r = nameSym "r" in
let astRec = bind_ (nulet_ r (urecord_ [("y", int_ 2), ("x", int_ 1)]))
                   (dprint_ (nvar_ r)) in
utest esCompileToString astRec with join
  [ "export default function main(env) {\n"
  , "  const r = { x: 1, y: 2 };\n"
  , "  env.dprint(r);\n"
  , "}\n" ] in

-- A tuple is a record whose fields are named "0", "1", ... They sort
-- numerically rather than lexicographically, so a 10-field tuple does not put
-- field 10 before field 2.
let astTup = bind_ (nulet_ r (utuple_ [int_ 10, int_ 20]))
                   (dprint_ (nvar_ r)) in
utest esCompileToString astTup with join
  [ "export default function main(env) {\n"
  , "  const r = { \"0\": 10, \"1\": 20 };\n"
  , "  env.dprint(r);\n"
  , "}\n" ] in

-- Projection reads the field directly. Tuple fields cannot be written with a
-- dot, so they are indexed.
let astProj = bind_ (nulet_ r (urecord_ [("x", int_ 1), ("y", int_ 2)]))
                    (dprint_ (recordproj_ "x" (nvar_ r))) in
utest esCompileToString astProj with join
  [ "export default function main(env) {\n"
  , "  const r = { x: 1, y: 2 };\n"
  , "  env.dprint(r.x);\n"
  , "}\n" ] in

let astTupProj = bind_ (nulet_ r (utuple_ [int_ 10, int_ 20]))
                       (dprint_ (tupleproj_ 1 (nvar_ r))) in
utest esCompileToString astTupProj with join
  [ "export default function main(env) {\n"
  , "  const r = { \"0\": 10, \"1\": 20 };\n"
  , "  env.dprint(r[1]);\n"
  , "}\n" ] in

-- Record update spreads the original.
let astUpd = bind_ (nulet_ r (urecord_ [("x", int_ 1), ("y", int_ 2)]))
                   (dprint_ (recordupdate_ (nvar_ r) "x" (int_ 9))) in
utest esCompileToString astUpd with join
  [ "export default function main(env) {\n"
  , "  const r = { x: 1, y: 2 };\n"
  , "  env.dprint({ ...r, x: 9 });\n"
  , "}\n" ] in

-- A record pattern reads only the fields it names -- there is no binding for
-- `y` here. The binding for `x` survives because it is used twice; used once
-- it would be inlined to `r.x`, as the projection tests above show.
let px = nameSym "px" in
let astPat = bind_ (nulet_ r (urecord_ [("x", int_ 1), ("y", int_ 2)]))
  (match_ (nvar_ r) (prec_ [("x", npvar_ px)])
     (dprint_ (addi_ (nvar_ px) (nvar_ px))) never_) in
utest esCompileToString astPat with join
  [ "export default function main(env) {\n"
  , "  const r = { x: 1, y: 2 };\n"
  , "  const px = r.x;\n"
  , "  env.dprint(px + px);\n"
  , "}\n" ] in

-- The empty record is unit, and the empty record pattern matches it.
let u = nameSym "u" in
let astUnit = bind_ (nulet_ u uunit_) (dprint_ (nvar_ u)) in
utest esCompileToString astUnit with join
  [ "export default function main(env) {\n"
  , "  const u = undefined;\n"
  , "  env.dprint(u);\n"
  , "}\n" ] in

-- ---------------------------------------------------------------------
-- Cleanup passes
-- ---------------------------------------------------------------------

-- The pattern lowerer binds every match scrutinee to a `_target`. Those are
-- compiler-introduced, pure and used once, so they are inlined away.
let t = nameSym "_target" in
let astTemp = bind_ (nulet_ t (lti_ (int_ 1) (int_ 2)))
  (dprint_ (if_ (nvar_ t) (int_ 1) (int_ 0))) in
utest esCompileToString astTemp with join
  [ "export default function main(env) {\n"
  , "  env.dprint(1 < 2 ? 1 : 0);\n"
  , "}\n" ] in

-- A name the programmer wrote is kept, even though inlining it would be
-- shorter: generated code is read while debugging, and the name is worth more.
let sum = nameSym "sum" in
let astNamed = bind_ (nulet_ sum (addi_ (int_ 1) (int_ 2)))
                     (dprint_ (nvar_ sum)) in
utest esCompileToString astNamed with join
  [ "export default function main(env) {\n"
  , "  const sum = 1 + 2;\n"
  , "  env.dprint(sum);\n"
  , "}\n" ] in

-- A temporary used twice stays, since inlining would duplicate the work.
let t2 = nameSym "_t" in
let astTwice = bind_ (nulet_ t2 (addi_ (int_ 1) (int_ 2)))
                     (dprint_ (addi_ (nvar_ t2) (nvar_ t2))) in
utest esCompileToString astTwice with join
  [ "export default function main(env) {\n"
  , "  const _t = 1 + 2;\n"
  , "  env.dprint(_t + _t);\n"
  , "}\n" ] in

-- An impure temporary stays too: the call has to happen, and where it was.
let t3 = nameSym "_t" in
let astImpure = bind_ (nulet_ t3 (dprint_ (int_ 1)))
                      (dprint_ (nvar_ t3)) in
utest esCompileToString astImpure with join
  [ "export default function main(env) {\n"
  , "  const _t = env.dprint(1);\n"
  , "  env.dprint(_t);\n"
  , "}\n" ] in

-- ---------------------------------------------------------------------
-- Sequences and strings
-- ---------------------------------------------------------------------

-- A character sequence prints as a string literal, spread into an array at
-- run time so that indexing stays O(1) and codepoint-correct.
let sq = nameSym "s" in
let astStr = bind_ (nulet_ sq (str_ "hi")) (print_ (nvar_ sq)) in
let strOut = esCompileToString astStr in
let contains = lam needle. lam s. gti (length (strSplit needle s)) 1 in
utest contains "const s = $S(\"hi\");" strOut with true in
-- The host takes a plain JS string and never sees the representation.
utest contains "env.print($jsStr(s));" strOut with true in
utest contains "function $S(s) {" strOut with true in
utest contains "function $jsStr(s) {" strOut with true in

-- A sequence of anything else is an array literal.
let astArr = bind_ (nulet_ sq (seq_ [int_ 1, int_ 2])) (dprint_ (nvar_ sq)) in
utest esCompileToString astArr with join
  [ "export default function main(env) {\n"
  , "  const s = [1, 2];\n"
  , "  env.dprint(s);\n"
  , "}\n" ] in

-- The common sequence operations are plain JS, not runtime calls.
let astOps = bind_ (nulet_ sq (seq_ [int_ 1, int_ 2]))
  (dprint_ (addi_ (length_ (nvar_ sq)) (get_ (nvar_ sq) (int_ 0)))) in
utest esCompileToString astOps with join
  [ "export default function main(env) {\n"
  , "  const s = [1, 2];\n"
  , "  env.dprint(s.length + s[0]);\n"
  , "}\n" ] in

let astCons = dprint_ (cons_ (int_ 0) (seq_ [int_ 1])) in
utest esCompileToString astCons with join
  [ "export default function main(env) {\n"
  , "  env.dprint([0, ...[1]]);\n"
  , "}\n" ] in

-- Every function value is a one-parameter arrow, so `map` hands its callback
-- straight to the JS method rather than wrapping it.
let astMap = dprint_ (map_ (nulam_ (nameSym "c") (int_ 1)) (seq_ [int_ 2])) in
utest contains "[2].map(c => 1)" (esCompileToString astMap) with true in

-- Only the operations needing a copy, a clamp or a pair go through the
-- runtime.
let astSub = dprint_ (subsequence_ (seq_ [int_ 1]) (int_ 0) (int_ 1)) in
utest contains "$subsequence([1], 0, 1)" (esCompileToString astSub) with true in

-- ---------------------------------------------------------------------
-- Constructors, recursion and tail calls
-- ---------------------------------------------------------------------

-- A datatype becomes a base class carrying the payload, and each constructor
-- a one-line subclass. `extends` is what records, in the output, that these
-- belong together: MExpr datatypes are open, so the constructors can be
-- declared far from the type.
let shape = nameSym "Shape" in
let circle = nameSym "Circle" in
let tyShape = ntycon_ shape in
let astCon = bindall_
  [ ntype_ shape [] (tyvariant_ [])
  , ncondef_ circle (tyarrow_ tyfloat_ tyShape) ]
  (dprint_ (nconapp_ circle (float_ 1.0))) in
utest esCompileToString astCon with join
  [ "export default function main(env) {\n"
  , "  class Shape { constructor(v) { this.v = v; } }\n"
  , "  class Circle extends Shape {}\n"
  , "  env.dprint(new Circle(1.0));\n"
  , "}\n" ] in

-- A type alias is erased entirely.
let al = nameSym "Alias" in
let astAlias = bind_ (ntype_ al [] tyint_) (dprint_ (int_ 1)) in
utest esCompileToString astAlias with join
  [ "export default function main(env) {\n"
  , "  env.dprint(1);\n"
  , "}\n" ] in

-- Matching a constructor is an `instanceof`, and the payload is the single
-- field the base class holds.
let sv = nameSym "s" in
let pv = nameSym "r" in
let astMatchCon = bindall_
  [ ntype_ shape [] (tyvariant_ [])
  , ncondef_ circle (tyarrow_ tyfloat_ tyShape)
  , nulet_ sv (nconapp_ circle (float_ 1.0)) ]
  (dprint_ (match_ (nvar_ sv) (npcon_ circle (npvar_ pv))
              (mulf_ (nvar_ pv) (float_ 2.0)) (float_ 0.0))) in
let conOut = esCompileToString astMatchCon in
let contains = lam needle. lam s. gti (length (strSplit needle s)) 1 in
-- The payload binding is used once, so it inlines and the branch folds back
-- into a ternary. Used twice it would stay an `if`, since inlining would
-- duplicate the field access.
utest contains "s instanceof Circle ? s.v * 2.0 : 0.0" conOut with true in

-- A self tail call becomes a jump to the top of the body rather than
-- recursion, so the stack does not grow.
let f = nameSym "loop" in
let n = nameSym "n" in
let astTail = bind_
  (nreclets_ [(f, tyunknown_, nulam_ n
     (if_ (lti_ (nvar_ n) (int_ 1)) (int_ 0)
          (app_ (nvar_ f) (subi_ (nvar_ n) (int_ 1)))))])
  (dprint_ (app_ (nvar_ f) (int_ 5))) in
utest esCompileToString astTail with join
  [ "export default function main(env) {\n"
  , "  function loop(n) {\n"
  , "    while (true) {\n"
  , "      if (n < 1) {\n"
  , "        return 0;\n"
  , "      } else {\n"
  , "        n = n - 1;\n"
  , "        continue;\n"
  , "      }\n"
  , "    }\n"
  , "  }\n"
  , "  env.dprint(loop(5));\n"
  , "}\n" ] in

-- With more than one parameter the rebinding goes through temporaries, so a
-- later argument cannot see an already-updated parameter. The cleanup pass
-- must not inline these away.
let g = nameSym "go" in
let acc = nameSym "acc" in
let astTail2 = bind_
  (nreclets_ [(g, tyunknown_, nulam_ n (nulam_ acc
     (if_ (lti_ (nvar_ n) (int_ 1)) (nvar_ acc)
          (appf2_ (nvar_ g) (subi_ (nvar_ n) (int_ 1))
                            (addi_ (nvar_ acc) (nvar_ n))))))])
  (dprint_ (appf2_ (nvar_ g) (int_ 5) (int_ 0))) in
let tail2 = esCompileToString astTail2 in
utest contains "const _arg = n - 1;" tail2 with true in
utest contains "const _arg_1 = acc + n;" tail2 with true in
utest contains "n = _arg;" tail2 with true in
utest contains "acc = _arg_1;" tail2 with true in

-- Recursion that is not in tail position stays a call.
let h = nameSym "count" in
let astNonTail = bind_
  (nreclets_ [(h, tyunknown_, nulam_ n
     (if_ (lti_ (nvar_ n) (int_ 1)) (int_ 0)
          (addi_ (int_ 1) (app_ (nvar_ h) (subi_ (nvar_ n) (int_ 1))))))])
  (dprint_ (app_ (nvar_ h) (int_ 5))) in
let nonTail = esCompileToString astNonTail in
utest contains "return n < 1 ? 0 : 1 + count(n - 1);" nonTail with true in
utest contains "while (true)" nonTail with false in

-- A user binding named `env` does not capture the runtime environment.
let userEnv = nameSym "env" in
let ast5 = bind_ (nulet_ userEnv (int_ 1)) (dprint_ (nvar_ userEnv)) in
utest esCompileToString ast5 with join
  [ "export default function main(env) {\n"
  , "  const env_1 = 1;\n"
  , "  env.dprint(env_1);\n"
  , "}\n" ] in

()
