let themeVariables = "
/* =========================
   THEME VARIABLES
   ========================= */

:root {
  --bodyBGColor: #f9fafb;
  --bodyTextColor: #111827;
  --h1BorderColor: #d1d5db;
  --h1Color: #111827;
  --h2Color: #1f2937;
  --h2BorderColor: #3b82f6;
  --topDocBorderColor: #d1d5db;
  --topDocColor: #1f2937;
  --topDocBgColor: #ffffff;
  --docBlockBGColor: #ffffff;
  --docBlockBorderColor: #3b82f6;
  --docBlockOutlineColor: #e5e7eb;
  --docSignatureBGColor: #f9f9f9;
  --docDescriptionBGColor: #f0f4ff;
  --docDescriptionBorderColor: #d1d5db;
  --docDescriptionTextColor: #374151;
  --codeBlockBGColor: #fafafa;
  --codeBlockBorderColor: #e5e7eb;
  --toggleHoverBGColor: #bae6fd;
  --gotoLinkColor: #3b82f6;
  --aColor: #2980b9;
  --keywordColor: #dc2626;
  --variableColor: #2563eb;
  --typeColor: #7c3aed;
  --numberColor: #0284c7;
  --commentColor: #16a34a;
  --stringColor: #008000;
  --multiColor: #a0a1a7;
  --searchBarBGColor: #f2f2f2;
  --searchBarTextColor: #1a1a1a;
  --searchBarPlaceholderColor: #777777;
  --searchBarShadowColor: rgba(0,0,0,0.1);
  --searchResultsBGColor: #ffffff;
  --searchResultsShadowColor: rgba(0,0,0,0.15);
  --searchResultItemBGColor: #fafafa;
  --searchResultItemTextColor: #333333;
  --searchResultItemHoverBGColor: #f0f0f0;
  --searchResultItemActiveBGColor: #d9d9d9;
  --searchResultItemBorderColor: rgba(0,0,0,0.08);
  --searchHighlightColor: #0066cc;
  --searchResultBGColor: #ffffff;
}

/* htmlLight */
:root[data-theme=\"htmlLight\"] {
  --bodyBGColor: #f9fafb;
  --bodyTextColor: #111827;
  --h1BorderColor: #d1d5db;
  --h1Color: #111827;
  --h2Color: #1f2937;
  --h2BorderColor: #3b82f6;
  --topDocBorderColor: #d1d5db;
  --topDocColor: #1f2937;
  --topDocBgColor: #ffffff;
  --docBlockBGColor: #ffffff;
  --docBlockBorderColor: #3b82f6;
  --docBlockOutlineColor: #e5e7eb;
  --docSignatureBGColor: #f9f9f9;
  --docDescriptionBGColor: #f0f4ff;
  --docDescriptionBorderColor: #d1d5db;
  --docDescriptionTextColor: #374151;
  --codeBlockBGColor: #fafafa;
  --codeBlockBorderColor: #e5e7eb;
  --toggleHoverBGColor: #bae6fd;
  --gotoLinkColor: #3b82f6;
  --aColor: #2980b9;
  --keywordColor: #dc2626;
  --variableColor: #2563eb;
  --typeColor: #7c3aed;
  --numberColor: #0284c7;
  --commentColor: #16a34a;
  --stringColor: #008000;
  --multiColor: #a0a1a7;
  --searchBarBGColor: #f2f2f2;
  --searchBarTextColor: #111827;
  --searchBarPlaceholderColor: #6b7280;
  --searchBarShadowColor: rgba(0,0,0,0.15);
  --searchResultsBGColor: #ffffff;
  --searchResultsShadowColor: rgba(0,0,0,0.2);
  --searchResultItemBGColor: #ffffff;
  --searchResultItemTextColor: #1f2937;
  --searchResultItemHoverBGColor: #f3f4f6;
  --searchResultItemActiveBGColor: #e5e7eb;
  --searchResultItemBorderColor: #e5e7eb;
  --searchHighlightColor: #3b82f6;
  --searchBarBGColor: #f2f2f2;
  --searchBarTextColor: #1a1a1a;
  --searchBarPlaceholderColor: #777777;
  --searchBarShadowColor: rgba(0,0,0,0.1);
  --searchResultsBGColor: #ffffff;
  --searchResultsShadowColor: rgba(0,0,0,0.15);
  --searchResultItemBGColor: #fafafa;
  --searchResultItemTextColor: #333333;
  --searchResultItemHoverBGColor: #f0f0f0;
  --searchResultItemActiveBGColor: #d9d9d9;
  --searchResultItemBorderColor: rgba(0,0,0,0.08);
  --searchHighlightColor: #0066cc;
  --searchResultBGColor: #ffffff;
}

/* htmlDark */
:root[data-theme=\"htmlDark\"] {
  --bodyBGColor: #0d0d0d;
  --bodyTextColor: #e5e5e5;
  --h1BorderColor: #2a2a2a;
  --h1Color: #ffffff;
  --h2Color: #d4d4d4;
  --h2BorderColor: #3b82f6;
  --topDocBorderColor: #2a2a2a;
  --topDocColor: #d0d0d0;
  --topDocBgColor: #121212;
  --docBlockBGColor: #1a1a1a;
  --docBlockBorderColor: #3b82f6;
  --docBlockOutlineColor: #333333;
  --docSignatureBGColor: #222222;
  --docDescriptionBGColor: #121212;
  --docDescriptionBorderColor: #3b82f6;
  --docDescriptionTextColor: #cccccc;
  --codeBlockBGColor: #0f0f0f;
  --codeBlockBorderColor: #2c2c2c;
  --toggleHoverBGColor: #0d0d0d;
  --gotoLinkColor: #3b82f6;
  --aColor: #3b82f6;
  --keywordColor: #f87171;
  --variableColor: #93c5fd;
  --typeColor: #fcd34d;
  --numberColor: #fbbf24;
  --commentColor: #86efac;
  --stringColor: #a8ff60;
  --multiColor: #6a9955;
  --searchBarBGColor: #1f1f1f;
  --searchBarTextColor: #e5e5e5;
  --searchBarPlaceholderColor: #aaaaaa;
  --searchBarShadowColor: rgba(0,0,0,0.4);
  --searchResultsBGColor: #121212;
  --searchResultsShadowColor: rgba(0,0,0,0.6);
  --searchResultItemBGColor: #2c2c2c;
  --searchResultItemTextColor: #f5f5f5;
  --searchResultItemHoverBGColor: #3a3a3a;
  --searchResultItemActiveBGColor: #555555;
  --searchResultItemBorderColor: rgba(255,255,255,0.08);
  --searchHighlightColor: #4da6ff;
  --searchResultBGColor: transparent;
}

/* htmlWarm */
:root[data-theme=\"htmlWarm\"] {
  --bodyBGColor: #fef7e0;
  --bodyTextColor: #3b3b2f;
  --h1BorderColor: #f4cd6b;
  --h1Color: #2b2b1f;
  --h2Color: #3a3000;
  --h2BorderColor: #f2b100;
  --topDocBorderColor: #f4cd6b;
  --topDocColor: #3b3b2f;
  --topDocBgColor: #fff9d1;
  --docBlockBGColor: #fffbe6;
  --docBlockBorderColor: #f2b100;
  --docBlockOutlineColor: #fce8b1;
  --docSignatureBGColor: #fff6cf;
  --docDescriptionBGColor: #fdf4c1;
  --docDescriptionBorderColor: #f2d96b;
  --docDescriptionTextColor: #3b3b2f;
  --codeBlockBGColor: #fefce8;
  --codeBlockBorderColor: #f5deb0;
  --toggleHoverBGColor: #ffffff;
  --gotoLinkColor: #e09b00;
  --aColor: #e09b00;
  --keywordColor: #c92a2a;
  --variableColor: #7048e8;
  --typeColor: #d97706;
  --numberColor: #c2410c;
  --commentColor: #5c940d;
  --stringColor: #d19a66;
  --multiColor: #b294bb;
  --searchBarBGColor: #fff9d1;
  --searchBarTextColor: #3b3b2f;
  --searchBarPlaceholderColor: #8c7a3d;
  --searchBarShadowColor: rgba(0,0,0,0.15);
  --searchResultsBGColor: #fffbe6;
  --searchResultsShadowColor: rgba(124, 90, 0, 0.2);
  --searchResultItemBGColor: #fffdf3;
  --searchResultItemTextColor: #3a3000;
  --searchResultItemHoverBGColor: #fef7e0;
  --searchResultItemActiveBGColor: #fce8b1;
  --searchResultItemBorderColor: #f5deb0;
  --searchHighlightColor: #e09b00;
  --searchResultBGColor: transparent;
}

/* htmlWarmDark */
:root[data-theme=\"htmlWarmDark\"] {
  --bodyBGColor: #1e1e1e;
  --bodyTextColor: #f5f5dc;
  --h1BorderColor: #facc15;
  --h1Color: #fef9c3;
  --h2Color: #fde68a;
  --h2BorderColor: #facc15;
  --topDocBorderColor: #facc15;
  --topDocColor: #e5e5c0;
  --topDocBgColor: #2a2a1f;
  --docBlockBGColor: #2b2b2b;
  --docBlockBorderColor: #facc15;
  --docBlockOutlineColor: #3f3f3f;
  --docSignatureBGColor: #3a3a3a;
  --docDescriptionBGColor: #343434;
  --docDescriptionBorderColor: #facc15;
  --docDescriptionTextColor: #e7e7c1;
  --codeBlockBGColor: #1c1c1c;
  --codeBlockBorderColor: #333333;
  --toggleHoverBGColor: #1e1e1e;
  --gotoLinkColor: #facc15;
  --aColor: #facc15;
  --keywordColor: #f87171;
  --variableColor: #93c5fd;
  --typeColor: #fcd34d;
  --numberColor: #fbbf24;
  --commentColor: #86efac;
  --stringColor: #ffcb0b;
  --multiColor: #c792e0;
  --searchBarBGColor: #2a2a1f;
  --searchBarTextColor: #f5f5dc;
  --searchBarPlaceholderColor: #c9c9a5;
  --searchBarShadowColor: rgba(0,0,0,0.5);
  --searchResultsBGColor: #2b2b2b;
  --searchResultsShadowColor: rgba(0,0,0,0.7);
  --searchResultItemBGColor: #3a3a3a;
  --searchResultItemTextColor: #fef9c3;
  --searchResultItemHoverBGColor: #444444;
  --searchResultItemActiveBGColor: #555533;
  --searchResultItemBorderColor: #3f3f3f;
  --searchHighlightColor: #facc15;
  --searchResultBGColor: transparent;
}

"
