#!/usr/bin/env bash

# Build a tarball with Miking and the necessary dependencies.
# Usage:
#
#     /path/to/miking$ scripts/miking-pack
#
# This produces a tarball 'miking-pack.tar.gz' with structure
#
#     miking-pack/
#       mi-env
#       bin/
#         mi
#       lib/
#         mcore/stdlib/
#         ...
#       miking-opam-switch/
#         bin/
#         lib/
#         ...
#
# 'mi-env' provides a script setting the necessary environment
# variables needed to run the Miking compiler and its compiled
# binaries.  To use the tarball, simply run
#
#     tar xzf miking-pack.tar.gz
#     . miking-pack/mi-env
#
# You will then be in an environment where 'mi' and its dependencies
# are available.
#
# To run this script, you need bash and nix.

# Force the script to exit upon error.
set -e

TMP_DIR="/tmp/miking-pack"

init_temp_dir() {
    echo "Making build directory at $TMP_DIR."
    rm -rvf $TMP_DIR
    mkdir -v $TMP_DIR
}

install_miking() {
    echo "Installing miking and dependencies to $TMP_DIR."
    dep_path="$(nix-build "$(dirname "${BASH_SOURCE[0]}")" -A miking --no-out-link)"
    nix-store --query --requisites "$dep_path" | while read dep_path; do
        cp -drnv $dep_path/* $TMP_DIR
        # Files copied from the nix store are unwritable, so update the permissions.
        chmod +w -R $TMP_DIR
    done
}

# patch_binaries() {
#     echo "Patching absolute paths in binaries."
#     find $TMP_DIR/bin -type f -exec patchelf --set-interpreter $FOO {} \;
# }

prepare_env() {
    echo "Preparing 'mi-env' script with the environment variables needed."
    cat <<'EOS' > $TMP_DIR/mi-env
export SOURCE="$(dirname "$(realpath -s "${BASH_SOURCE[0]}")")"
export OCAMLPATH="$SOURCE/lib/ocaml:$SOURCE/lib/ocaml/5.0.0/site-lib"
export OCAMLLIB="$SOURCE/lib/ocaml"
export PATH="$SOURCE/bin"
export LIBRARY_PATH="$SOURCE/lib"
export LD_LIBRARY_PATH="$LIBRARY_PATH"
export MCORE_LIBS="stdlib=$SOURCE/lib/mcore/stdlib"
unset  OPAM_SWITCH_PREFIX
EOS
}

make_tarball() {
    init_temp_dir
    install_miking
    prepare_env
    tar -C /tmp -czvf miking-pack.tar.gz ./miking-pack
}

make_tarball
