#!/bin/bash

echo "Generate file..."
gcc -O3 gen.c && a.out > f.txt
ls -l f.txt
echo

echo "** Fast read test in C **"
gcc -O3 readtest.c
time a.out 
echo

echo "** Fast read test in Ocaml **"
ocamlbuild readtest.native 
time readtest.native
echo

echo "** Count test in C **"
gcc -O3 readcount.c
time a.out 
echo

echo "** Read count 1 in Ocaml **"
ocamlbuild readcount1.native 
time readcount1.native
echo

echo "** Read count 2 in Ocaml **"
ocamlbuild readcount2.native 
time readcount2.native
echo

echo "** Grep **"
time grep '[123]+' f.txt 
echo


echo "Clean up..."
rm -rf f.txt a.out *.byte *.native _build
