#!/bin/bash

echo "Generate file..."
gcc gen.c && a.out > f.txt
ls -l f.txt
echo

echo "** Fast read test in C **"
gcc readtest.c
time a.out
echo

echo "** Grep **"
time grep '[123]+' f.txt
echo


echo "Clean up..."
rm -rf f.txt a.out
